spring:
  application:
    name: ai-xlei-zerocode-platform-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_xlei_zerocode
    username: root
    password: 123456
server:
  port: 8090
  servlet:
    context-path: /api

# springdoc-openapi
# ????Swagger: http://localhost:8090/api/doc.html#/home
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xlei.zerocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn